declare function back(): boolean;
declare function home(): boolean;
declare function powerDialog(): boolean;
declare function notifications(): boolean;
declare function quickSettings(): boolean;
declare function recents(): boolean;
declare function splitScreen(): boolean;
declare function Home(): void;
declare function Back(): void;
declare function Power(): void;
declare function Menu(): void;
declare function VolumeUp(): void;
declare function VolumeDown(): void;
declare function Camera(): void;
declare function Up(): void;
declare function Down(): void;
declare function Left(): void;
declare function Right(): void;
declare function OK(): void;
declare function Text(text: string): void;
declare function KeyCode(code: number | string): void;
