name: NodeJS with Webpack

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js current
      uses: actions/setup-node@v3
      with:
        node-version: current

    - name: Build
      run: |
        npm install
        npm test
        npm run report-coverage
        npm run build

    - name: production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MiuiCleaner
        retention-days: 7
        path: |
          dist/miui_cleaner_cmd/MiuiCleaner.cmd
          dist/miui_cleaner_app/services.js
          dist/miui_cleaner_app/main.js

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/miui_cleaner_cmd/MiuiCleaner.cmd
          dist/miui_cleaner_app/services.js
          dist/miui_cleaner_app/main.js
